### ISSUE TITLE
Android bugs

### ISSUE THREAD

**Issue by hifriend21** [lukebrandonfarrell/react-native-images-collage#1]
There is strange behaviour when I'm trying to drag image on android device. It start jumping from top to bottom. I suppose it depends on image resolution, because it happens when img height > img width.
Also I'm not able to zoom it by touch in this case

**Comment by LukeBrandonFarrell** [comment]
@hifriend21 I'm still looking into doing a rewrite of this library, so hang tight... I should have some free time at the end of this month.

**Comment by lukebrandonfarrell** [comment]
@hifriend21 The library has been rewritten and most major bugs have been fixed. This should now be fixed.
